hardwareproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from users.views import store_registration


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', store_registration, name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
# from .views import SellProductsView
# from .views import save_sale

urlpatterns = [
    path('', views.homepage, name='home'),
    # path('make-sale/', views.make_sale, name='make_sale'),
    
    path('add-product/', views.add_product, name='add_product'),
    path('sell-products/', views.sell_products, name='sell_products'),
    path('products/', views.products, name='stocks'),
    path('inventory/value/', views.inventory_value_report, name='value_report'),
    path('logout/', views.logout_view, name='logout_view'),
    path('sold_products/', views.sold_products, name='sold_products'),
    # path('get_product_details/', views.get_product_details, name='get_product_details'),
    path('generate_pdf_receipt/<int:sale_id>/', views.generate_pdf_receipt, name='generate_pdf_receipt'),
    path('download_receipt/<int:sale_id>/', views.download_receipt, name='download_receipt'),
    path('reorder-point-products/', views.reorder_point_products, name='reorder_point_products'),
    path('quick-inventory-adjustment/', views.quick_inventory_adjustment, name='quick_inventory_adjustment'),
    path('quick-price-adjustment/', views.quick_price_adjustment, name='quick_price_adjustment'),
    path('print-receipt/', views.print_receipt, name='print_receipt'),
    path('import-products/', views.import_products, name='import_products'),
    # path('save-sale/', save_sale, name='save_sale'),
    # path('counter/', SellProductsView.as_view(), name='sell_products'),
    # path('sales/return/', views.sales_return, name='sales_return'),
    # path('return/<int:product_id>/', views.perform_sales_return, name='perform_sales_return'),
    path('daily/', views.daily_sales_report, name='daily_sales_report'),
    path('weekly/', views.weekly_sales_report, name='weekly_sales_report'),
    path('monthly/', views.monthly_sales_report, name='monthly_sales_report'),
    path('yearly/', views.yearly_sales_report, name='yearly_sales_report'),
    path('search-product/', views.search_product, name='search_product'),
    path('top-selling/', views.top_selling_products, name='top_selling_products'),
    path('stock_data/', views.stock_data, name='stock'),
    path('sales-reports/', views.sales_reports, name='sales-reports'),
    path('sell/success/', views.sales_success, name='sales_success'),
    path('<int:product_id>/update/', views.update_product, name='update_product'),
    path('<int:product_id>/delete/', views.delete_product, name='delete_product'),
   
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

class Store(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    inventory_quantity = models.PositiveIntegerField()
    standard_price = models.DecimalField(max_digits=10, decimal_places=2)
    current_cost = models.DecimalField(max_digits=10, decimal_places=2)
    reorder_point = models.PositiveIntegerField()


    def __str__(self):
        return self.name

class Sale(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    sale_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    
    class Meta:
        ordering = ('-sale_date',)


    def get_total_price(self):
        return self.quantity * self.product.standard_price

users/models.py
from django.db import models

# Create your models here.

store/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User


class ProductNameForm(forms.Form):
    name = forms.CharField(label='Product Name', widget=forms.TextInput(attrs={'autofocus': True}))
    # quantity = forms.IntegerField(label='Quantity', widget=forms.NumberInput(attrs={'min': 1}))

    def clean_name(self):
        name = self.cleaned_data['name']
        try:
            # Searching by product name instead of barcode
            product = Product.objects.get(name=name)
        except Product.DoesNotExist:
            raise forms.ValidationError('Product with this name does not exist.')
        return product
    
    # def clean_quantity(self):
    #     quantity = self.cleaned_data['quantity']
    #     if quantity <= 0:
    #         raise forms.ValidationError('Quantity must be greater than 0.')
    #     return quantity

# class BarcodeForm(forms.Form):
#     barcode = forms.IntegerField(label='Barcode', widget=forms.TextInput(attrs={'autofocus': True}))

#     def clean_barcode(self):
#         barcode = self.cleaned_data['barcode']
#         try:
#             product = Product.objects.get(barcode=barcode)
#         except Product.DoesNotExist:
#             raise forms.ValidationError('Product with this barcode does not exist.')
#         return product
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'inventory_quantity', 'standard_price', 'current_cost', 'reorder_point']

users/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User
from store.models import Store

class StoreRegistrationForm(forms.ModelForm):
    username = forms.CharField(max_length=150)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Store
        fields = ['name', 'address']  # Add other fields from Store model as needed

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

    def save(self, commit=True):
        user = User.objects.create_user(
            username=self.cleaned_data['username'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password']
        )
        store = super().save(commit=False)
        store.user = user
        if commit:
            store.save()
        return store

users/views.py
# views.py
from django.shortcuts import render, redirect
from .forms import StoreRegistrationForm

def store_registration(request):
    if request.method == 'POST':
        form = StoreRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to login page after successful registration
    else:
        form = StoreRegistrationForm()
    return render(request, 'users/store_registration.html', {'form': form})

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
  <link rel="stylesheet" href="index.css">
  <title>Login</title>
  <style>
    /* Background white */
:root {
  --bg1: #e8eaec;
  --text-color: #979797;
  --color: #000;
  --tcolor: rgb(119 119 119);

  --boxShadow: 7px 7px 15px #45566754, -8px -8px 15px rgb(81 101 121 / 4%),
    inset -5px -4px 13px 0px rgb(81 101 121 / 35%),
    inset 6px 7px 12px 0px rgb(255 255 255 / 94%);

  --boxShadow2: inset 4px 4px 8px rgb(189 200 213),
    inset -4px -4px 8px rgb(255 255 255);

  --boxShadow3: inset 4px 4px 8px rgb(189 200 213),
    inset -4px -4px 8px rgb(255 255 255);

  --sbShadow: 5px 5px 7px rgb(0 0 0 /25%),
    inset 2px 2px 5px rgb(255 255 255 / 25%),
    inset -3px -3px 5px rgb(0 0 0 / 12%);
}

/* Background dark */
body.dark {
  --bg1: #2f363e;
  --text-color: rgb(255 208 0);
  --color: #fff;
  --tcolor: rgb(36, 6, 6);

  --boxShadow: 5px 5px 15px rgb(0, 0, 0, 0.25), 5px 15px 15px rgb(0, 0, 0, 0.25),
    inset 5px 5px 10px rgb(0, 0, 0, 0.5),
    inset 5px 5px 20px rgb(255, 255, 255, 0.2),
    inset -5px -5px 15px rgb(0, 0, 0, 0.75);

  --boxShadow2: inset -3px -3px 6px rgb(73, 78, 83),
    inset 3px 3px 6px rgb(32, 28, 28);

  --boxShadow2: -3px -3px 6px rgb(73, 78, 83), 3px 3px 6px rgb(32, 28, 28);

  --sbShadow: 5px 5px 7px rgb(0 0 0 /25%),
    inset 2px 2px 5px rgb(255 255 255 / 25%),
    inset -3px -3px 5px rgb(0 0 0 / 12%);
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: serif;
}

html,
body {
  height: 100%;
}

body {
  display: grid;
  place-items: center;
  text-align: center;
  background: var(--bg1);
}

.content {
  width: 385px;
  background: var(--bg1);
  box-shadow: var(--boxShadow);
  border-radius: 20px;
  padding: 60px 40px;
  margin-top: 45px;
}

.content .text {
  font-size: 33px;
  font-size: 600;
  margin-bottom: 35px;
  color: var(--color);
}

.content .field {
  height: 50px;
  width: 100%;
  display: flex;
  position: relative;
}

.field input {
  height: 40px;
  width: 100%;
  padding-left: 50px;
  font-size: 15px;
  outline: none !important;
  border: none;
  background: var(bg1);
  box-shadow: var(--boxShadow2);
  border-radius: 25px;
}

input:focus {
  box-shadow: var(--boxShadow);
}
::placeholder {
  color: var(--tcolor);
}

.field:nth-child(2) {
  margin-top: 20px;
}

.field:nth-child(3) {
  margin-top: 20px;
}

.field span {
  position: absolute;
  width: 50px;
  line-height: 50px;
  color: var(--tcolor);
  font-size: 22px;
}

button {
  margin: 25px 0;
  width: 80px;
  height: 40px;
  color: var(--color);
  font-size: 18px;
  font-weight: 600;
  background: var(--bg1);
  border: none;
  outline: none;
  cursor: pointer;
  box-shadow: var(--boxShadow);
  border-radius: 25px;
}

button:focus {
  color: #ff6100;
  box-shadow: var(--boxShadow2);
}

h4 {
  font-size: 14px;
  color: rgb(119 119 119);
  margin: 0 0 16px 0;
}

.social_icons {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
}

.social_icons i {
  line-height: 50px;
  height: 50px;
  width: 50px;
  color: #fff;
  border-radius: 50%;
  box-shadow: var(--sbShadow);
  font-size: 28px;
}

.foot {
  margin: 20px auto;
  color: rgb(119 119 119);
}

.in {
  color: #ff6100;
  text-decoration: none;
}

.in:hover {
  text-decoration: underline;
}

.social_icons i:nth-child(1) {
  /* background-image: linear-gradient(315deg,#0078ff -7.64,#00c6ff 104.5%); */
  background-image: linear-gradient(315deg, #0078ff, #00c6ff);
}

.social_icons i:nth-child(1):hover {
  color: #0078ff;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.social_icons i:nth-child(2) {
  /* background-image: linear-gradient(315deg,#4949e7 -6.1,#5eb2fc 101.5%); */
  background-image: linear-gradient(315deg, #4949e7, #5eb2fc);
}

.social_icons i:nth-child(2):hover {
  color: #5662e9;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.social_icons i:nth-child(3) {
  /* background-image: linear-gradient(315deg,#02b7ff -7.64,#92cdfa 104.5%); */
  background-image: linear-gradient(315deg, #02b7ff, #92cdfa);
}

.social_icons i:nth-child(3):hover {
  color: #00acee;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.social_icons i:nth-child(4) {
  /* background-image: linear-gradient(315deg,#02b7ff -7.64,#92cdfa 104.5%); */
  background-image: linear-gradient(315deg, #b9215c, #de4882);
}

.social_icons i:nth-child(4):hover {
  color: #de4882;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.dark-light {
  left: 50px;
  display: flex;
  position: absolute;
  justify-content: center;
  align-items: center;
  top: 50px;
  width: 60px;
  height: 60px;
  box-shadow: var(--boxShadow);
  border-radius: 50px;
}

.dark-light i {
  position: absolute;
  color: var(--tcolor);
  font-size: 25px;
  cursor: pointer;
  transition: all 0.3s ease;
}

.dark-light i.sun {
  opacity: 0;
  pointer-events: none;
}

.dark-light.active i.sun {
  opacity: 1;
  pointer-events: auto;
}

.dark-light.active i.moon {
  opacity: 0;
  pointer-events: none;
}
/* Custom styles for small devices */
@media (max-width: 576px) {
            .content {
                width: 90%;
                padding: 20px;
            }
            .content .text {
                font-size: 24px;
            }
            .field input {
                padding-left: 40px;
            }
        }
  </style>
</head>

<body>
  <div class="content">
    <div class="text">Login</div>
    <form method="post">
        {% csrf_token %}
      <div class="field">
        <span class="bx bxs-user"></span>
        <input type="username" name="username" placeholder="Username" required>
      </div>

      <div class="field">
        <span class="bx bxs-lock-alt"></span>
        <input type="password" name="password" placeholder="Password" required>
      </div>

      <button>Login</button>
      <h4>Don't Have an Account? <a href="{% url 'register' %}" style="color: #00c6ff;">Register Now</a></h4>
      <br>
      <h4>or Login with social platforms</h4>

      <div class="social_icons">
        <i class="bx bxl-facebook"></i>
        <i class="bx bxl-discord-alt"></i>
        <i class="bx bxl-twitter"></i>
        <i class="bx bxl-dribbble"></i>
      </div>

      
    </form>

    <div class="dark-light" onclick="myFunction()">
      <i class="bx bx-moon moon"></i>
      <i class="bx bx-sun sun"></i>
    </div>
  </div>
  <script>
    const body = document.querySelector("body"),
      modeToggle = document.querySelector(".dark-light");
    modeToggle.addEventListener("click", () => {
      modeToggle.classList.toggle("active");
      body.classList.toggle("dark");
      if (!body.classList.contains("dark")) {
        localStorage.setItem("mode", "light-mode");
      } else {
        localStorage.setItem("mode", "dark-mode");
      }
    })
  </script>
</body>

</html>

users/templates/users/store_registration.html
<!-- store_registration.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <title>Store Registration</title>
    <!-- Add MDBootstrap CSS link -->
    <!-- Font Awesome -->
  <style>
    /* Background white */
:root {
  --bg1: #e8eaec;
  --text-color: #979797;
  --color: #000;
  --tcolor: rgb(119 119 119);

  --boxShadow: 7px 7px 15px #45566754, -8px -8px 15px rgb(81 101 121 / 4%),
    inset -5px -4px 13px 0px rgb(81 101 121 / 35%),
    inset 6px 7px 12px 0px rgb(255 255 255 / 94%);

  --boxShadow2: inset 4px 4px 8px rgb(189 200 213),
    inset -4px -4px 8px rgb(255 255 255);

  --boxShadow3: inset 4px 4px 8px rgb(189 200 213),
    inset -4px -4px 8px rgb(255 255 255);

  --sbShadow: 5px 5px 7px rgb(0 0 0 /25%),
    inset 2px 2px 5px rgb(255 255 255 / 25%),
    inset -3px -3px 5px rgb(0 0 0 / 12%);
}

/* Background dark */
body.dark {
  --bg1: #2f363e;
  --text-color: rgb(255 208 0);
  --color: #fff;
  --tcolor: rgb(36, 6, 6);

  --boxShadow: 5px 5px 15px rgb(0, 0, 0, 0.25), 5px 15px 15px rgb(0, 0, 0, 0.25),
    inset 5px 5px 10px rgb(0, 0, 0, 0.5),
    inset 5px 5px 20px rgb(255, 255, 255, 0.2),
    inset -5px -5px 15px rgb(0, 0, 0, 0.75);

  --boxShadow2: inset -3px -3px 6px rgb(73, 78, 83),
    inset 3px 3px 6px rgb(32, 28, 28);

  --boxShadow2: -3px -3px 6px rgb(73, 78, 83), 3px 3px 6px rgb(32, 28, 28);

  --sbShadow: 5px 5px 7px rgb(0 0 0 /25%),
    inset 2px 2px 5px rgb(255 255 255 / 25%),
    inset -3px -3px 5px rgb(0 0 0 / 12%);
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: serif;
}

html,
body {
  height: 100%;
}

body {
  display: grid;
  place-items: center;
  text-align: center;
  background: var(--bg1);
}

.content {
  width: 385px;
  background: var(--bg1);
  box-shadow: var(--boxShadow);
  border-radius: 20px;
  padding: 60px 40px;
  margin-top: 45px;
}

.content .text {
  font-size: 33px;
  font-size: 600;
  margin-bottom: 35px;
  color: var(--color);
}

.content .field {
  height: 50px;
  width: 100%;
  display: flex;
  position: relative;
}

.field input {
  height: 40px;
  width: 100%;
  padding-left: 50px;
  font-size: 15px;
  outline: none !important;
  border: none;
  background: var(bg1);
  box-shadow: var(--boxShadow2);
  border-radius: 25px;
}

input:focus {
  box-shadow: var(--boxShadow);
}
::placeholder {
  color: var(--tcolor);
}

.field:nth-child(2) {
  margin-top: 20px;
}

.field:nth-child(3) {
  margin-top: 20px;
}

.field span {
  position: absolute;
  width: 50px;
  line-height: 50px;
  color: var(--tcolor);
  font-size: 22px;
}

button {
  margin: 25px 0;
  width: 80px;
  height: 40px;
  color: var(--color);
  font-size: 18px;
  font-weight: 600;
  background: var(--bg1);
  border: none;
  outline: none;
  cursor: pointer;
  box-shadow: var(--boxShadow);
  border-radius: 25px;
}

button:focus {
  color: #ff6100;
  box-shadow: var(--boxShadow2);
}

h4 {
  font-size: 14px;
  color: rgb(119 119 119);
  margin: 0 0 16px 0;
}

.social_icons {
  display: flex;
  justify-content: space-evenly;
  align-items: center;
}

.social_icons i {
  line-height: 50px;
  height: 50px;
  width: 50px;
  color: #fff;
  border-radius: 50%;
  box-shadow: var(--sbShadow);
  font-size: 28px;
}

.foot {
  margin: 20px auto;
  color: rgb(119 119 119);
}

.in {
  color: #ff6100;
  text-decoration: none;
}

.in:hover {
  text-decoration: underline;
}

.social_icons i:nth-child(1) {
  /* background-image: linear-gradient(315deg,#0078ff -7.64,#00c6ff 104.5%); */
  background-image: linear-gradient(315deg, #0078ff, #00c6ff);
}

.social_icons i:nth-child(1):hover {
  color: #0078ff;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.social_icons i:nth-child(2) {
  /* background-image: linear-gradient(315deg,#4949e7 -6.1,#5eb2fc 101.5%); */
  background-image: linear-gradient(315deg, #4949e7, #5eb2fc);
}

.social_icons i:nth-child(2):hover {
  color: #5662e9;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.social_icons i:nth-child(3) {
  /* background-image: linear-gradient(315deg,#02b7ff -7.64,#92cdfa 104.5%); */
  background-image: linear-gradient(315deg, #02b7ff, #92cdfa);
}

.social_icons i:nth-child(3):hover {
  color: #00acee;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.social_icons i:nth-child(4) {
  /* background-image: linear-gradient(315deg,#02b7ff -7.64,#92cdfa 104.5%); */
  background-image: linear-gradient(315deg, #b9215c, #de4882);
}

.social_icons i:nth-child(4):hover {
  color: #de4882;
  background-image: linear-gradient(
    to bottom,
    #e8eaec,
    rgba(189, 200, 213, 0.795)
  );
  text-shadow: 2px 2px 3px #b8b9be, -2px -2px -2px #fff;
}

.dark-light {
  left: 50px;
  display: flex;
  position: absolute;
  justify-content: center;
  align-items: center;
  top: 50px;
  width: 60px;
  height: 60px;
  box-shadow: var(--boxShadow);
  border-radius: 50px;
}

.dark-light i {
  position: absolute;
  color: var(--tcolor);
  font-size: 25px;
  cursor: pointer;
  transition: all 0.3s ease;
}

.dark-light i.sun {
  opacity: 0;
  pointer-events: none;
}

.dark-light.active i.sun {
  opacity: 1;
  pointer-events: auto;
}

.dark-light.active i.moon {
  opacity: 0;
  pointer-events: none;
}
/* Custom styles for small devices */
@media (max-width: 576px) {
            .content {
                width: 90%;
                padding: 20px;
            }
            .content .text {
                font-size: 24px;
            }
            .field input {
                padding-left: 40px;
            }
        }
  </style>
</head>
<body>
    
        
        
            
                <div class="content">
                    <h1 class="text">Signup</h1>
                <form method="POST">
                    {% csrf_token %}
                    <div class="field">
                        <span class="bx bxs-user"></span>
                        <input type="text" id="id_username" name="username" placeholder="Username" class="form-control" required>
                        <!-- <label class="form-label" for="id_username">Username</label> -->
                    </div>
                    <div class="field">
                        <span class="bx bxs-envelope"></span>
                        <input type="email" id="id_email" name="email" placeholder="Email" class="form-control" required>
                        <!-- <label class="form-label" for="id_email">Email</label> -->
                    </div>
                    
                    <div class="field">
                        <span class="bx bxs-building"></span>
                        <input type="text" id="id_name" name="name" placeholder="Store Name" class="form-control">
                        <!-- <label class="form-label" for="id_name">Store Name</label> -->
                    </div>
                    <div class="field">
                        <span class="bx bxs-location-plus"></span>
                        <input type="text" id="id_address" name="address" placeholder="Address" class="form-control" required>
                        <!-- <label class="form-label" for="id_address">Address</label> -->
                    </div>
                    <div class="field">
                        <span class="bx bxs-lock-alt"></span>
                        <input type="password" id="id_password" name="password" placeholder="Password" class="form-control" required>
                        <!-- <label class="form-label" for="id_password">Password</label> -->
                    </div>
                    <button type="submit">signup</button>
                </form>
                <div class="dark-light" onclick="myFunction()">
                    <i class="bx bx-moon moon"></i>
                    <i class="bx bx-sun sun"></i>
                  </div>
                <hr>
                <h4>I Have an Account? <a href="{% url 'login' %}" style="color: #00c6ff;">Login Now</h4></p>
            </div>
            
            
        
    
    <!-- Add MDBootstrap JavaScript link -->
    <!-- MDB -->

<script>
    const body = document.querySelector("body"),
      modeToggle = document.querySelector(".dark-light");
    modeToggle.addEventListener("click", () => {
      modeToggle.classList.toggle("active");
      body.classList.toggle("dark");
      if (!body.classList.contains("dark")) {
        localStorage.setItem("mode", "light-mode");
      } else {
        localStorage.setItem("mode", "dark-mode");
      }
    })
  </script>
</body>
</html>